name: Branching test

on:
  push:
    branches:
      - 'CI-release/**'


jobs:
  deploy:
    name: Branching test
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: fix git permissions
        run: git config --global --add safe.directory /__w/github-actions-branch-test/github-actions-branch-test

      - name: verify git tag exists
        run: git describe --tags --abbrev=0
